### ISSUE TITLE
not work with zepto v1.1.6

### ISSUE THREAD

**Issue by tenstep** [ciaoca/cxDialog#1]

**Comment by ciaoca** [comment]
Need Zepto modules [data](https://github.com/madrobby/zepto/blob/master/src/data.js) support

**Comment by tenstep** [comment]
i have added the data module by zeptobuilder, however, it seems that the error doesn't matter with the data module. I got the error tip that the jQuery is not defined in line 34, the screen shotcut is as follow:
![image](https://cloud.githubusercontent.com/assets/2585654/5995289/6226f2ba-aaca-11e4-8dfe-7e7625c30b83.png)

**Comment by ciaoca** [comment]
you can download the latest version

```
factory(window.jQuery || window.Zepto || window.$);
```

**Comment by tenstep** [comment]
thanks, the latest version works.
